def build_summary_row(terminal, current, t1_5, t2, t3, q_at_ig, diag):
    return {
        '故障端': terminal,
        '故障类型': diag['Fault_Type'],
        '故障严重度': diag['Fault_Severity'],
        '故障回路': diag['Fault_Circuit_ID'],
        'Case_ID': diag['Case_ID'],
        '电流工况': diag['Current_Profile'],
        '环境温度 (°C)': diag['Ambient_Temp_C'],
        '通风状态': diag['Vent_State'],
        '门状态': diag['Door_State'],
        '故障开始时间 (s)': diag['T_Fault_Start_s'],
        '供电类型': diag['Supply_Mode'],
        '测试电流 (A)': current,
        '服役年限': diag['Service_Years'],
        '老化综合因子': diag['Aging_Eta_Total'],
        '老化后活化能 (kJ/mol)': diag['Aging_Ea_kJ_per_mol'],
        '微弧前兆起始时间 (s)': round(t1_5, 3) if t1_5 is not None else None,
        '稳定产弧时间 (s)': round(t2, 3) if t2 is not None else None,
        '微弧过渡期时长 (s)': round(t2 - t1_5, 3) if (t2 is not None and t1_5 is not None) else None,
        '起火时间 (s)': round(t3, 3) if t3 is not None else None,
        '引燃瞬间有效弧能 (J)': round(q_at_ig, 1) if q_at_ig is not None else None,
        '峰值电弧功率 (W)': diag['Peak_Arc_Power_W'],
        '峰值故障端电压 (V)': diag['Peak_Fault_Voltage_V'],
        '峰值芯温 (°C)': diag['Peak_Core_T_C'],
        '峰值火源热释放 (kW)': round(diag['Peak_Fire_HRR_W'] / 1000.0, 3),
        '微弧可观测采样点': diag['Stage_1_5_Samples'],
        '交流过零次数': diag['AC_Zero_Crossings'],
        '交流重燃次数': diag['AC_Reignitions'],
        '点燃节点数': diag['Nodes_Ignited'],
        '模型能力标签': diag['Capability_Tag'],
        '主要局限': diag['Limitation_Tag'],
    }
